# version: '3.8'

# services:
#   mysql-user:
#     image: mysql:8
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: userlist
#     ports:
#       - "3307:3306"
#     networks:
#       - backend

#   mysql-product:
#     image: mysql:8
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: productlist
#     ports:
#       - "3308:3306"
#     networks:
#       - backend

#   mysql-cart:
#     image: mysql:8
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: cart_db
#     ports:
#       - "3309:3306"
#     networks:
#       - backend

#   mysql-order:
#     image: mysql:8
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: orders_db
#     ports:
#       - "3310:3306"
#     networks:
#       - backend

#   userservice:
#     build: ./userservice
#     ports:
#       - "8081:8081"
#     depends_on:
#       - mysql-user
#     environment:
#       - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-user:3306/userlist?allowPublicKeyRetrieval=true&useSSL=false
#       - SPRING_DATASOURCE_USERNAME=root
#       - SPRING_DATASOURCE_PASSWORD=root
#     networks:
#       - backend

#   productservice:
#     build: ./productservice
#     ports:
#       - "8082:8082"
#     depends_on:
#       - mysql-product
#     environment:
#       - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-product:3306/productlist?allowPublicKeyRetrieval=true&useSSL=false
#       - SPRING_DATASOURCE_USERNAME=root
#       - SPRING_DATASOURCE_PASSWORD=root
#     networks:
#       - backend

#   cartservice:
#     build: ./cartservice
#     ports:
#       - "8083:8083"
#     depends_on:
#       - mysql-cart
#     environment:
#       - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-cart:3306/cart_db?allowPublicKeyRetrieval=true&useSSL=false
#       - SPRING_DATASOURCE_USERNAME=root
#       - SPRING_DATASOURCE_PASSWORD=root
#     networks:
#       - backend

#   orderservice:
#     build: ./orderservice
#     ports:
#       - "8084:8084"
#     depends_on:
#       - mysql-order
#     environment:
#       - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-order:3306/orders_db?allowPublicKeyRetrieval=true&useSSL=false
#       - SPRING_DATASOURCE_USERNAME=root
#       - SPRING_DATASOURCE_PASSWORD=root
#     networks:
#       - backend

#   apigateway:
#     build: ./apigateway
#     ports:
#       - "8080:8080"
#     depends_on:
#       - userservice
#       - productservice
#       - cartservice
#       - orderservice
#     networks:
#       - backend

#   frontend:
#     build: ./frontend
#     ports:
#       - "80:80"
#     depends_on:
#       - apigateway
#     networks:
#       - backend

# networks:
#   backend:








version: '3.8'

services:
  mysql-user:
    image: mysql:8
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userlist
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  mysql-product:
    image: mysql:8
    container_name: mysql-product
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productlist
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  mysql-cart:
    image: mysql:8
    container_name: mysql-cart
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cart_db
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  mysql-order:
    image: mysql:8
    container_name: mysql-order
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders_db
    ports:
      - "3310:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  userservice:
    build: ./userservice
    ports:
      - "8081:8081"
    depends_on:
      mysql-user:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-user:3306/userlist?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - backend

  productservice:
    build: ./productservice
    ports:
      - "8082:8082"
    depends_on:
      mysql-product:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-product:3306/productlist?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - backend

  cartservice:
    build: ./cartservice
    ports:
      - "8083:8083"
    depends_on:
      mysql-cart:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-cart:3306/cart_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - backend

  orderservice:
    build: ./orderservice
    ports:
      - "8084:8084"
    depends_on:
      mysql-order:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-order:3306/orders_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - backend

  apigateway:
    build: ./apigateway
    ports:
      - "8080:8080"
    depends_on:
      - userservice
      - productservice
      - cartservice
      - orderservice
    networks:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - apigateway
    networks:
      - backend

networks:
  backend:

